version: "3"

services:
  mysql:
    build: ./database/
    restart: always
    env_file: ./database/.env
    ports:
      - "3307:3307"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppass"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - backend
  myadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3307
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - backend

volumes:
  mysql:
networks:
  backend: